This is makeindex, version 2.17 [TeX Live 2023] (kpathsea + Thai support).
Scanning style file ./msc-thesis.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file msc-thesis.acn....done (481 entries accepted, 0 rejected).
Sorting entries.......done (4516 comparisons).
Generating output file msc-thesis.acr....done (259 lines written, 0 warnings).
Output written in msc-thesis.acr.
Transcript written in msc-thesis.alg.
